# Generated by Django 5.0.6 on 2024-05-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=5)),
                ('tamano', models.CharField(choices=[('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=8)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('fecha_agregada', models.DateField(auto_now_add=True)),
                ('adoptada', models.BooleanField(default=False)),
            ],
        ),
    ]
