# Generated by Django 5.0.6 on 2024-05-17 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría de mascotas',
                'verbose_name_plural': 'categorías de mascotas',
            },
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'mascota', 'verbose_name_plural': 'mascotas'},
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='adoptada',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_agregada',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='categoria_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascota.mascotacategoria', verbose_name='categoría de mascota'),
        ),
    ]
