# Generated by Django 5.0.6 on 2024-05-18 21:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20240518_1621'),
    ]

    operations = [
        migrations.AddField(model_name="mascota", name="adoptada", field=models.BooleanField(default=False))
    ]
